version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3

jobs:
  lint-dockerfile:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)
  
  build-app-karsajobs:
    executor: docker/docker
    environment:
      IMAGE_NAME: ghcr.io/ymasterous/karsajobs
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to GitHub Container Registry
          command: |
            echo "$CR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  ci:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app